spring:
  application:
    name: WeTube-service
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

clerk:
  jwks-url: ${JWKS_URL}