spring:
  application:
    name: WeTube-service
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


clerk:
  jwks-url: ${JWKS_URL}

management:
  endpoints:
    web:
      cors:
        allowed-origins:
          - ${CORS_ALLOWED_ORIGINS}
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowed-headers: *
        exposed-headers:
          - "Authorization"
        allow-credentials: true
        max-age: 3600