spring.application.name=WeTube-service

# spring.datasource.url=jdbc:mysql://avnadmin:AVNS_ny5penLSLIESJdZRPeL@mysql-3c9f4204-shinizeam-668c.b.aivencloud.com:16344/defaultdb?ssl-mode=REQUIRED
# spring.datasource.username=avnadmin
# spring.datasource.password=AVNS_ny5penLSLIESJdZRPeL

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

