spring:
  config:
    import: optional:file:.env.local.properties
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD}
#      database: ${REDIS_DATABASE}
#      timeout: ${REDIS_TIMEOUT}ms
#      jedis:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
#          max-wait: -1ms

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

management:
  endpoints:
    web:
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS}
        allowed-methods: ${CORS_ALLOWED_METHODS}
        allowed-headers: ${CORS_ALLOWED_HEADERS}
        exposed-headers: ${CORS_EXPOSED_HEADERS}
        allow-credentials: ${CORS_ALLOW_CREDENTIALS}
        max-age: 3600